var nameMap = {
   "sig" : {  
        "11":{  
           "CTP_ENG_NM":"Seoul",
           "AIR_NM":"seoul"
        },
        "26":{  
           "CTP_ENG_NM":"Busan",
           "AIR_NM":"busan"
        },
        "27":{  
           "CTP_ENG_NM":"Daegu",
           "AIR_NM":"daegu"
        },
        "28":{  
           "CTP_ENG_NM":"Incheon",
           "AIR_NM":"incheon"
        },
        "29":{  
           "CTP_ENG_NM":"Gwangju",
           "AIR_NM":"gwangju"
        },
        "30":{  
           "CTP_ENG_NM":"Daejeon",
           "AIR_NM":"daejeon"
        },
        "31":{  
           "CTP_ENG_NM":"Ulsan",
           "AIR_NM":"ulsan"
        },
        "36":{  
           "CTP_ENG_NM":"Sejong-si",
           "AIR_NM":"sejong"
        },
        "41":{  
           "CTP_ENG_NM":"Gyeonggi-do",
           "AIR_NM":"gyeonggi"
        },
        "42":{  
           "CTP_ENG_NM":"Gangwon-do",
           "AIR_NM":"gangwon"
        },
        "43":{  
           "CTP_ENG_NM":"Chungcheongbuk-do",
           "AIR_NM":"chungbuk"
        },
        "44":{  
           "CTP_ENG_NM":"Chungcheongnam-do",
           "AIR_NM":"chungnam"
        },
        "45":{  
           "CTP_ENG_NM":"Jeollabuk-do",
           "AIR_NM":"jeonbuk"
        },
        "46":{  
           "CTP_ENG_NM":"Jellanam-do",
           "AIR_NM":"jeonnam"
        },
        "47":{  
           "CTP_ENG_NM":"Gyeongsangbuk-do",
           "AIR_NM":"gyeongbuk"
        },
        "48":{  
           "CTP_ENG_NM":"Gyeongsangnam-do",
           "AIR_NM":"gyeongnam"
        },
        "50":{  
           "CTP_ENG_NM":"Jeju-do",
           "AIR_NM":"jeju"
        }
     },
     "emd" : {
        
     }
   }

export default nameMap